### ISSUE TITLE
pygame.error: File is not a Windows BMP file

### ISSUE THREAD

**Issue by keenan-v1** [tobykurien/rpi_lcars#27]
Raspberry Pi 4 running Raspbian Buster Slim using the Adafruit 7" Touchscreen display.

Using ./run.sh gets me to this error message:
```
Traceback (most recent call last):
  File "lcars.py", line 8, in <module>
    config.SOUND)
  File "/home/pi/rpi_lcars/app/ui/ui.py", line 30, in __init__
    self.screen.setup(self.all_sprites)
  File "/home/pi/rpi_lcars/app/screens/authorize.py", line 16, in setup
    all_sprites.add(LcarsBackgroundImage("assets/lcars_screen_2.png"),
  File "/home/pi/rpi_lcars/app/ui/widgets/background.py", line 14, in __init__
    self.image = pygame.image.load(image).convert()
pygame.error: File is not a Windows BMP file
```
I've verified that Pillow is installed and all needed libraries are installed. Any assistance would be appreciated.

**Comment by FCPTRiddle** [comment]
I have the same exact problem, running Raspberry Pi 4 with 4gb memory and Raspbian Buster full OS on a 10.1 inch touch screen display. Please help

**Comment by tobykurien** [comment]
I searched the error message and found some posts, maybe this is relevant: https://stackoverflow.com/questions/25120883/how-to-uninstall-pygame-on-mac-osx-10-9-4

**Comment by topcats** [comment]
just had the same issue after dist-upgrade to Buster.

the resolution was the fact the SDL libraries were not installed.

**Comment by FCPTRiddle** [comment]
I am still new to raspberry pi. If the resolution is the SDL libraries were not installed how do I install those?

Please help

Eric Riddle
e_riddle@icloud.com

**Comment by topcats** [comment]
The easiest way, will be install using the command line

1. Open a terminal window
2. sudo apt update
3. sudo apt install libsdl-gfx1.2-5 libsdl-image1.2 libsdl-kitchensink1 libsdl-mixer1.2 libsdl-sound1.2 libsdl-ttf2.0-0 libsdl1.2debian libsdl2-2.0-0 libsdl2-gfx-1.0-0 libsdl2-image-2.0-0 libsdl2-mixer-2.0-0 libsdl2-ttf-2.0-0
4. Try again, all should be good.

**Comment by Scinape** [comment]
> 

Thank you very much! I met the same problem on my Raspberry Pi, thanks to you it's solved :)

**Comment by bluush** [comment]
nice one, was chasing my tail for a while and topcats instruction fixed it.
