### ISSUE TITLE
No module named utils

### ISSUE THREAD

**Issue by VoicelessProximity1701** [tobykurien/rpi_lcars#38]
I get this error when i try to run the program:

Traceback (most recent call last):
  File "lcars.py", line 2, in <module>
    from ui.ui import UserInterface
  File "/home/praveetminash/rpi_lcars-master/app/ui/ui.py", line 4, in <module>
    from ui.utils import sound
ImportError: No module named utils

**Comment by GozuMezu** [comment]
I have the exact same issue

**Comment by garrettrathbone** [comment]
I ran into the same issue until I updated to the newest version of python 3. Before that, I just removed the 'ui.' portion and it allowed it run, although I still can't get audio to work.

**Comment by VoicelessProximity1701** [comment]
Thanks a lot!

**Comment by JDat** [comment]
Why you run this as root. Running it as root is total nonsence. Run as user. Also remember that pulseaudio service is running as user not as root.

**Comment by JDat** [comment]
This is not tested with rpi_lcars on RPi, but for other poruses I am using user lingering for autorun apps in linux with specific nonroot user. See second answer:
https://askubuntu.com/questions/676007/how-do-i-make-my-systemd-service-run-via-specific-user-and-start-on-boot

**Comment by MCDevel** [comment]
i still have the problem. does anyone has other waysto fx it

**Comment by JDat** [comment]
Please provide detailed information how you launch lcars. Maye there are wrong path in .sh script.
Maybe you are launching it with python2.
Maybe pygame sound not installed.

While code is not production ready (it is ready for hobby), we can't not guess what are your problems. even worse, we don't know your linux and raspberry pi experience.

Need more info! Please!

**Comment by MCDevel** [comment]
i installt 3 versions of pygame i enabled the sound on multiple ways and still not working

**Comment by JDat** [comment]
Is is not important what you done. It is important how you done that.
Please post full console text.

Also please post alsa/pulse sound test results to confirm that audio is working (arecord/audacity).
Also test any pygame audio example code to make shure pygame sound working.
How you be shure that you are launching lcars with python3 and not python2 (consale dump as proof).

**Comment by MCDevel** [comment]
ok i will do later when i start my pi again
