### ISSUE TITLE
start erro

### ISSUE THREAD

**Issue by MCDevel** [tobykurien/rpi_lcars#40]
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "lcars.py", line 2, in <module>
    from ui.ui import UserInterface
  File "/home/pi/rpi_lcars-master/app/ui/ui.py", line 4, in <module>
    from ui.utils import sound
ImportError: No module named utils

**Comment by tobykurien** [comment]
Duplicate of #38

**Comment by MCDevel** [comment]
i tryed the solution from #38 but it still not working 
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "lcars.py", line 2, in <module>
    from ui.ui import UserInterface
  File "/home/pi/rpi_lcars-master/app/ui/ui.py", line 4, in <module>
    from ui.utils import sound
ImportError: No module named utils
